### ISSUE TITLE
Unable to skip tests

### ISSUE THREAD

**Issue by cqlii** [sam-cogan/arm-ttk-extension-xplatform#11]
When using the skipTests input the list of tests doesn't seem to be passing through correctly.

```
- task: RunARMTTKTestsXPlat@1
  inputs:
   templateLocation: infra.json
   skipTest: apiVersions Should Be Recent
   allTemplatesMain: false
```
Running this I get an error in the pipeline and the test is not skipped

```
WARNING: Test 'Should' was not found, all tests will be run
```
I've tried a couple different tests with the same issue. Seems to error with the second word of the test. I've also tried with and without quotes and with the test name all lower case. Any ideas?
