### ISSUE TITLE
When using a comma separated lists for -skiptest get a parameter 'clientSecret' error

### ISSUE THREAD

**Issue by bm-fez** [sam-cogan/arm-ttk-extension-xplatform#27]
## Issue
I have just migrated from the Windows PowerShell to this Cross Platform version. The only change I thought we required was in the task name swapping to

```yaml
- task: RunARMTTKTestsXPlat@1
  displayName: "Run ARM TTK tests on built ARM"
  inputs:
    templatelocation: '$(Build.SourcesDirectory)\BicepTemplates\ARMoutputs\*.json'
    resultLocation: '$(System.DefaultWorkingDirectory)\results'
    skipTests: '$(TestsToSkip)'
    cliOutputResults: true
``` 
However I have found that if have a comma separated list for `-skipTests` we get the following error

> Using executable 'powershell.exe'
> powershell.exe E:\Agent\_work\_tasks\RunARMTTKTestsXPlat_cb27e003-8534-4da9-aaa0-35ca8756ae29\1.2.1\powershell\ps-runner.ps1 -templateLocation E:\Agent\_work\17\s\BicepTemplates\ARMoutputs\*.json -resultLocation E:\Agent\_work\17\s\results -skipTests VM Images Should Use Latest Version,Resources Should Have Location,Location Should Not Be Hardcoded,Template Should Not Contain Blanks,DeploymentTemplate Must Not Contain Hardcoded Uri,Outputs Must Not Contain Secrets,URIs Should Be Properly Constructed -cliOutputResults -recurse
> ##[error]E:\Agent\_work\_tasks\RunARMTTKTestsXPlat_cb27e003-8534-4da9-aaa0-35ca8756ae29\1.2.1\powershell\ps-runner.ps1 : Cannot 
>
>##[error]E:\Agent\_work\_tasks\RunARMTTKTestsXPlat_cb27e003-8534-4da9-aaa0-35ca8756ae29\1.2.1\powershell\ps-runner.ps1 : Cannot 
>
> ##[error]process argument transformation on parameter 'clientSecret'. Cannot convert value to type System.String.
At line:1 char:265
> ... ults -skipTests VM Images Should Use Latest Version,Resources Should  ...
>     CategoryInfo          : InvalidData: (:) [ps-runner.ps1], ParameterBindingArgumentTransformationException
>     FullyQualifiedErrorId : ParameterArgumentTransformationError,ps-runner.ps1

## Analysis
Experimentation of running the `ps-runner.ps1` from the command prompt on a self hosted build agent showed that the solution was to enclose the skip test list for the inner PowerShell running in quotes.

```
powershell\ps-runner.ps1 -templateLocation E:\Agent\_work\17\s\BicepTemplates\ARMoutputs\*.json -resultLocation E:\Agent\_work\17\s\results -skipTests 'VM Images Should Use Latest Version,Resources Should Have Location,Location Should Not Be Hardcoded,Template Should Not Contain Blanks,DeploymentTemplate Must Not Contain Hardcoded Uri,Outputs Must Not Contain Secrets,URIs Should Be Properly Constructed' -cliOutputResults -recurse
```
Once this was done ARM TTK ran as expected.

Have I missed something related to parameter passing, am I passing in the list incorrectly?

I will link a PR with this change to this issue on the assumption this fix is valid. I have assumed the same fix is needed for the `includeTests` parameter
