### ISSUE TITLE
Exception calling "Replace"  with "2" argument(s): "The RegEx engine has timed out while trying to match a pattern to an input string'

### ISSUE THREAD

**Issue by bm-fez** [sam-cogan/arm-ttk-extension-xplatform#30]
## Issue
When this task is run within an Azure DevOps pipeline a Windows agent the following error is sometimes seen

> ##[error]Import-Json : Import failed for 
> 'E:\Agent\_work\92\s\Src\Expenses\BlackMarble.ISS.Bicep\ARMOutput\RootTemplate-Main.json': Exception calling "Replace" 
with "2" argument(s): "The RegEx engine has timed out while trying to match a pattern to an input string. This can 
occur for many reasons, including very large inputs or excessive backtracking caused by nested quantifiers, 
back-references and other factors." Exception calling "Replace" with "2" argument(s): "The RegEx engine has timed out 
while trying to match a pattern to an input string. This can occur for many reasons, including very large inputs or 
excessive backtracking caused by nested quantifiers, back-references and other factors." Exception calling "Replace" 
with "2" argument(s): "The RegEx engine has timed out while trying to match a pattern to an input string. This can 
occur for many reasons, including very large inputs or excessive backtracking caused by nested quantifiers, 

I suspect the issue is down to the complexity of the ARM template being analyzed 

## Analysis
If I RDP onto my on prem self hosted agent VM I can get the same error if I follow the following process

### From Command Prompt with PowerShell
1. Open a Command Prompt (CMD)
2. Run the command `powershell.exe E:\Agent\_work\_tasks\RunARMTTKTestsXPlat_cb27e003-8534-4da9-aaa0-35ca8756ae29\1.2.2\powershell\ps-runner.ps1 -templateLocation E:\Agent\_work\92\s\Src\Expenses\BlackMarble.ISS.Bicep\ARMOutput\* -resultLocation E:\Agent\_work\92\s -recurse  `
3. The same error as seen in a pipeline run is seen

![image](https://github.com/sam-cogan/arm-ttk-extension-xplatform/assets/104062511/f4ee0405-fbb6-4ccb-a513-1f700a833f04)

### From Command Prompt with PowerShell Core
1. Open a Command Prompt (CMD)
2. Run the command `pwsh.exe E:\Agent\_work\_tasks\RunARMTTKTestsXPlat_cb27e003-8534-4da9-aaa0-35ca8756ae29\1.2.2\powershell\ps-runner.ps1 -templateLocation E:\Agent\_work\92\s\Src\Expenses\BlackMarble.ISS.Bicep\ARMOutput\* -resultLocation E:\Agent\_work\92\s -recurse  `
3. The script runs as expect (I do have ARM TTK issue with the file under test)

![image](https://github.com/sam-cogan/arm-ttk-extension-xplatform/assets/104062511/5ee0286f-5502-47a0-b664-dc47137f779d)

### From PowerShell 5 Prompt 
1. Open a PowerShell 5 Prompt
2. Run the command `E:\Agent\_work\_tasks\RunARMTTKTestsXPlat_cb27e003-8534-4da9-aaa0-35ca8756ae29\1.2.2\powershell\ps-runner.ps1 -templateLocation E:\Agent\_work\92\s\Src\Expenses\BlackMarble.ISS.Bicep\ARMOutput\* -resultLocation E:\Agent\_work\92\s -recurse  `
3. The script fails  as expected

![image](https://github.com/sam-cogan/arm-ttk-extension-xplatform/assets/104062511/62a9ce76-e5fd-422c-aa3a-7eee6be6d239)

### From PowerShell 7 Prompt 
1. Open a PowerShell 7 Prompt
2. Run the command `E:\Agent\_work\_tasks\RunARMTTKTestsXPlat_cb27e003-8534-4da9-aaa0-35ca8756ae29\1.2.2\powershell\ps-runner.ps1 -templateLocation E:\Agent\_work\92\s\Src\Expenses\BlackMarble.ISS.Bicep\ARMOutput\* -resultLocation E:\Agent\_work\92\s -recurse  `
3. The script runs as expected (I do have ARM TTK issue with the file under test)

![image](https://github.com/sam-cogan/arm-ttk-extension-xplatform/assets/104062511/f2da3bed-37ad-42ed-9666-97fc31ea3227)

## Suggestion
The issue appears to be the use of the PowerShell 5 (powerhell.exe) as opposed to PowerShell 7 (pwsh.exe).  I think the best option is to give the user the choice to force the use of PWSH, whilst leaving the current default behavior as it is

I will create a PR with this change

 

> Note: This maybe replaced to the problem (arm-ttk-extension #10)[https://github.com/sam-cogan/arm-ttk-extension/issues/10)

**Comment by bm-fez** [comment]
Just looked that the source and realized `usePSCore` already exists, once set to true this fixed the parsing problem.

```yaml
# Generate the ARM from the Bicep
 - task: BicepBuild@0
    inputs:
      process: 'multiple'
      sourceDirectory: '$(Build.SourcesDirectory)\Src\Bicep\RootTemplate-*.bicep'
      stdout: false
      outputDirectory: '$(Build.SourcesDirectory)\Src\Bicep\ARMOutput' # Only when 'stdout' is false or not defined

 # Good practice to version your ARM
  - task: VersionJSONFile@2
    inputs:
      Path: '$(Build.SourcesDirectory)\Src\Bicep\ARMOutput'
      recursion: true
      VersionNumber: '$(Build.BuildNumber)'
      useBuildNumberDirectly: False
      VersionRegex: '\d+\.\d+\.\d+\.\d+'
      versionForJSONFileFormat: '{1}.{2}.{3}.{4}'
      FilenamePattern: '\w+.json'
      Field: 'contentVersion'
      OutputVersion: 'OutputedVersion'

  - task: RunARMTTKTestsXPlat@1
    displayName: 'Run ARM-TTK on all ARM templates'
    inputs:
      templatelocation: '$(Build.SourcesDirectory)\Src\Bicep\ARMOutput\*'
      resultLocation: '$(Build.SourcesDirectory)'
      usePSCore: true
    continueOnError: true
    
 - task: PublishTestResults@2
    displayName: 'Publish ARM-TTK test results'
    inputs:
      testResultsFormat: 'NUnit'
      testResultsFiles: '$(Build.SourcesDirectory)\*-armttk.xml'
      testRunTitle: 'Run_$(Build.BuildNumber)'
      failTaskOnFailedTests: true
```

Hopefully save some other people some time if they hit this issue
