### ISSUE TITLE
Warnings treated as errors which fails the pipeline step

### ISSUE THREAD

**Issue by mehowq** [sam-cogan/arm-ttk-extension-xplatform#36]
I've got the ARM TTK Tests (Cross Platform) extension version 1.0.27 installed in Azure DevOps

One of the pipelines has the following task configured:
```
- task: RunARMTTKTestsXPlat@1
  displayName: Scan Bicep files
  continueOnError: true
  inputs:
    templatelocation: '$(System.DefaultWorkingDirectory)'
    resultLocation: '$(System.DefaultWorkingDirectory)/results'
    allTemplatesMain: false
    cliOutputResults: true
    ignoreExitCode: false
    mainTemplates: 'main.bicep'

```
Since we must deploy Azure App Registrations through Bicep we use the following section in our bicepconfig.json:
```
{
"experimentalFeaturesEnabled": {
    "extensibility": true
  }
}
```

This allows us to create the App Registrations like so:
```
resource clientAppRegistration 'Microsoft.Graph/applications@v1.0' = {
  displayName: 'test'
  uniqueName: 'test' 
}
resource clientAppRegistrationSp 'Microsoft.Graph/servicePrincipals@v1.0' = {
  appId: clientAppRegistration.appId
}
```

Since we use the experimental mode the bicep linter throws the following warning:
"WARNING: The following experimental Bicep features have been enabled: Extensibility. Experimental features should be enabled for testing purposes only, as there are no guarantees about the quality or stability of these features. Do not enable these settings for any production usage, or your production environment may be subject to breaking."

This warning comes out in the pipeline step run:
![Screenshot 2024-12-03 132524_2](https://github.com/user-attachments/assets/8094f005-784b-4cdb-8960-d61f9ebc8b9e)

I did a bit of research and it looks like there's no way to disable this warning message.

My aim is to make this run appear as green rather than red or orange (with continueOnError enabled).
Is there a way to disable treating the warning messages as error messages?
